'use client';
import { Component, type ReactNode } from 'react';
import { ArrowUpRight, CircleHelp, RefreshCw, ShieldAlert } from 'lucide-react';
import { Badge, DataTable, Empty, EventFeed, Panel } from './primitives';
import { Button } from './ui/button';
import { TradingChart } from './chart';
import { OrderTicket } from './order-ticket';
import type { Action } from './action-dialog';
import { Display } from '@/lib/format';
import { ApiClient } from '@/lib/api';
import { ApiSchema, type Snapshot, type Strategy } from '@/lib/schema';
import type { z } from 'zod';

export type ViewProps = Readonly<{ snapshot: Snapshot; disabled: boolean; onAction: (action: Action) => void; api: ApiClient }>;
export class OverviewView extends Component<ViewProps> {
  render() { const data = this.props.snapshot.overview; return <><div className="metrics"><Metric label="Day P&L" value={Display.money(data?.day_pnl)} detail="Reported by the worker" tone={Display.tone(data?.day_pnl)} /><Metric label="Realised" value={Display.money(data?.realised_pnl)} detail="Closed positions · net of fees" tone={Display.tone(data?.realised_pnl)} /><Metric label="Unrealised" value={Display.money(data?.unrealised_pnl)} detail="Marked open positions" tone={Display.tone(data?.unrealised_pnl)} /><Metric label="Open positions" value={data ? String(data.open_positions) : '—'} detail={data ? `${data.open_orders} open orders` : 'Awaiting session data'} /></div><div className="content-grid"><div className="stack"><Panel title="Session performance" eyebrow="Intraday" action={<Badge>INR</Badge>}>{data?.equity_curve.length ? <TradingChart points={data.equity_curve} label="Worker-reported session performance in INR" /> : <Empty title="Waiting for session performance">The worker’s equity series will appear when available.</Empty>}<div className="panel-footer"><span>India Standard Time</span><span>Worker-reported values</span></div></Panel><Panel title="Open positions" action={<a className="text-link" href="/positions">View all <ArrowUpRight size={15} /></a>}><PositionsTable {...this.props} compact /></Panel></div><div className="stack"><Panel title="Session guardrails" eyebrow="At a glance"><div className="health-list"><Health name="Trading worker" healthy={data?.worker_healthy} /><Health name="Broker connection" healthy={data?.broker_healthy} /><Health name="Market feed" healthy={data?.feed_healthy} /></div><div className="guardrail-note"><ShieldAlert size={18} /><p>{data?.kill_switch ? 'Kill switch is active. New orders are halted.' : 'Every order is evaluated by the risk engine before execution.'}</p></div><a href="/risk" className="panel-link">Inspect risk limits <ArrowUpRight size={16} /></a></Panel><Panel title="Session activity"><EventFeed events={data?.events ?? []} /></Panel></div></div></>; }
}
export class Metric extends Component<{ label: string; value: string; detail: string; tone?: string }> { render() { return <section className="metric"><span>{this.props.label}</span><strong className={this.props.tone}>{this.props.value}</strong><small>{this.props.detail}</small></section>; } }
export class Health extends Component<{ name: string; healthy: boolean | undefined }> { render() { return <div className="health-row"><span>{this.props.name}</span><span className={this.props.healthy === undefined ? 'muted' : this.props.healthy ? 'positive' : 'negative'}><i className="status-dot" />{this.props.healthy === undefined ? 'Unknown' : this.props.healthy ? 'Healthy' : 'Unhealthy'}</span></div>; } }
export class PositionsTable extends Component<ViewProps & { compact?: boolean }> {
  render() { const items = this.props.snapshot.positions?.items ?? []; return <DataTable headings={['Instrument', 'Quantity', 'Avg. price', 'Last price', 'Unrealised P&L', ...(this.props.compact ? [] : ['Action'])]} rows={items.map(position => ({ id: position.id, cells: [<div key="symbol"><strong>{position.symbol}</strong><small className="cell-sub">{position.exchange} · {position.strategy_id}{position.frozen && ' · FROZEN'}</small></div>, position.quantity, Display.money(position.average_price), Display.money(position.last_price), <span key="pnl" className={Display.tone(position.unrealised_pnl)}>{Display.money(position.unrealised_pnl)}</span>, ...(this.props.compact ? [] : [<Button key="close" variant="secondary" size="sm" disabled={this.props.disabled || position.frozen || position.quantity === 0} onClick={() => this.props.onAction({ title: 'Close position', description: `Close ${position.symbol} using risk-approved limit orders. Execution and fills are not guaranteed.`, confirmation: `CLOSE ${position.symbol}`, danger: true, draft: { type: 'CLOSE_POSITION', params: { position_id: position.id } } })}>Close position</Button>])] }))} empty="No open positions" />; }
}
export class PositionsView extends Component<ViewProps> { render() { return <Panel title="Position ledger" action={<Badge>Cash equity · Intraday</Badge>}><PositionsTable {...this.props} /></Panel>; } }
export class OrdersView extends Component<ViewProps, { selected: string | null; filter: string }> {
  state = { selected: null as string | null, filter: 'all' };
  render() { const all = this.props.snapshot.orders?.items ?? []; const rows = all.filter(order => this.state.filter === 'all' || (this.state.filter === 'open' ? !['FILLED', 'CANCELLED', 'REJECTED', 'EXPIRED'].includes(order.state) : order.state === 'UNKNOWN')); const selected = all.find(order => order.id === this.state.selected); return <div className="content-grid"><div className="stack"><Panel title="Order book" action={<select aria-label="Filter orders" value={this.state.filter} onChange={event => this.setState({ filter: event.target.value })}><option value="all">All orders</option><option value="open">Open orders</option><option value="unknown">Unknown outcomes</option></select>}><DataTable headings={['Instrument', 'Side / Type', 'Filled / Qty', 'Limit', 'State', 'Actions']} rows={rows.map(order => ({ id: order.id, cells: [<div key="symbol"><strong>{order.symbol}</strong><small className="cell-sub">{Display.time(order.created_at)} IST</small></div>, <div key="side"><span className={order.side === 'BUY' ? 'positive' : 'negative'}>{order.side}</span><small className="cell-sub">{order.order_type}</small></div>, `${order.filled_quantity} / ${order.quantity}`, Display.money(order.limit_price), <Badge key="state" tone={order.state === 'UNKNOWN' ? 'warning' : ''}>{order.state}</Badge>, <div key="actions" className="row-actions"><Button size="sm" variant="ghost" onClick={() => this.setState({ selected: order.id })}>History</Button><Button size="sm" variant="secondary" disabled={this.props.disabled || !['OPEN', 'PARTIALLY_FILLED', 'TRIGGER_PENDING', 'ACKNOWLEDGED'].includes(order.state)} onClick={() => this.props.onAction({ title: 'Cancel order', description: `Request cancellation of ${order.symbol}. A concurrent fill may still occur; the worker confirms the final state.`, draft: { type: 'CANCEL_ORDER', params: { order_id: order.id } } })}>Cancel</Button></div>] }))} empty="No orders in this view" /></Panel><Panel title={selected ? `${selected.symbol} · Order history` : 'Order history'}>{selected ? <ol className="timeline">{selected.events.map(event => <li key={event.sequence}><span className="sequence">{event.sequence}</span><div><strong>{event.state}</strong><p>{event.message}</p><time>{Display.time(event.at)} IST</time></div></li>)}</ol> : <Empty title="Select an order’s history">Inspect every persisted transition in sequence.</Empty>}</Panel></div><OrderTicket market={this.props.snapshot.market} disabled={this.props.disabled} onAction={this.props.onAction} /></div>; }
}
export class StrategyCard extends Component<{ strategy: Strategy; disabled: boolean; onAction: (action: Action) => void }, { editing: boolean; text: string; error: string | null }> {
  constructor(props: Readonly<{ strategy: Strategy; disabled: boolean; onAction: (action: Action) => void }>) { super(props); this.state = { editing: false, text: JSON.stringify(props.strategy.config, null, 2), error: null }; }
  private review = () => {
    try { const config = ApiSchema.strategy.shape.config.parse(JSON.parse(this.state.text)); this.props.onAction({ title: 'Update strategy config', description: 'The worker validates this configuration and rejects mid-session changes. Review the before/after values below before submitting.', draft: { type: 'UPDATE_STRATEGY_CONFIG', params: { strategy_id: this.props.strategy.id, config, force: false } } }); this.setState({ error: null }); }
    catch { this.setState({ error: 'Enter a valid JSON object for the strategy configuration.' }); }
  };
  render() { const strategy = this.props.strategy; const running = strategy.status === 'running'; return <Panel title={strategy.name} eyebrow={strategy.id} action={<Badge tone={running ? 'positive' : strategy.status === 'halted' ? 'negative' : ''}>{strategy.status}</Badge>}><div className="strategy-body"><p className="muted">{strategy.description}</p><div className="strategy-stats"><div><small>Day P&L</small><strong className={Display.tone(strategy.pnl)}>{Display.money(strategy.pnl)}</strong></div><div><small>Signals</small><strong>{strategy.signals}</strong></div></div><div className="row-actions"><Button variant={running ? 'secondary' : 'default'} disabled={this.props.disabled || ['starting', 'stopping'].includes(strategy.status)} onClick={() => this.props.onAction({ title: running ? 'Stop strategy' : 'Start strategy', description: running ? `Gracefully stop ${strategy.name}. Existing positions stay open.` : `Request that the worker start ${strategy.name}. Risk gates remain active.`, draft: { type: running ? 'STOP_STRATEGY' : 'START_STRATEGY', params: { strategy_id: strategy.id } } })}>{running ? 'Stop strategy' : 'Start strategy'}</Button><Button variant="ghost" onClick={() => this.setState({ editing: !this.state.editing, text: JSON.stringify(strategy.config, null, 2) })}>Edit configuration</Button></div>{this.state.editing && <div className="config-editor"><label className="field">Proposed configuration<textarea rows={8} spellCheck={false} value={this.state.text} onChange={event => this.setState({ text: event.target.value })} /></label><details open><summary>Diff preview · current → proposed</summary><div className="diff-grid"><pre aria-label="Current configuration">{JSON.stringify(strategy.config, null, 2)}</pre><pre aria-label="Proposed configuration">{this.state.text}</pre></div></details>{this.state.error && <p role="alert" className="negative">{this.state.error}</p>}<Button variant="secondary" disabled={this.props.disabled || running || this.state.text === JSON.stringify(strategy.config, null, 2)} onClick={this.review}>Review configuration</Button>{running && <p className="small muted">Stop the strategy before requesting a configuration update.</p>}</div>}</div></Panel>; }
}
export class StrategiesView extends Component<ViewProps> { render() { const items = this.props.snapshot.strategies?.items ?? []; return items.length ? <div className="strategy-grid">{items.map(strategy => <StrategyCard key={strategy.id} strategy={strategy} disabled={this.props.disabled} onAction={this.props.onAction} />)}</div> : <Panel title="Strategies"><Empty title="No strategies registered">Configured strategies will appear when published by the worker.</Empty></Panel>; } }
export class RiskView extends Component<ViewProps> { render() { return <div className="content-grid"><Panel title="Risk limits" eyebrow="Worker-enforced"><div className="limits">{this.props.snapshot.risk?.limits.map(limit => <div className="limit" key={limit.name}><div><strong>{limit.name}</strong><span className="mono">{limit.used.toLocaleString('en-IN')} / {limit.limit.toLocaleString('en-IN')} {limit.unit}</span></div><meter min={0} max={limit.limit} value={limit.used} aria-label={limit.name} /><small className="muted">{Math.round(limit.used / limit.limit * 100)}% utilised</small></div>)}</div>{!this.props.snapshot.risk?.limits.length && <Empty title="Limits unavailable">Connect to the worker to inspect its configured risk limits.</Empty>}</Panel><Panel title="Risk decisions"><EventFeed events={this.props.snapshot.risk?.events ?? []} empty="No risk decisions recorded" /></Panel></div>; } }
export class MarketView extends Component<ViewProps, { instrument: string; interval: string; candles: z.infer<typeof ApiSchema.candles> | null; error: string | null; loading: boolean }> {
  state = { instrument: '', interval: '5m', candles: null as z.infer<typeof ApiSchema.candles> | null, error: null as string | null, loading: false };
  private abort: AbortController | null = null;
  private timer: ReturnType<typeof setInterval> | null = null;
  componentDidMount() { this.timer = setInterval(() => { if (this.state.instrument && !this.state.loading) void this.load(); }, 2000); }
  componentWillUnmount() { this.abort?.abort(); if (this.timer) clearInterval(this.timer); }
  private async load() {
    this.abort?.abort(); const abort = new AbortController(); this.abort = abort; this.setState({ loading: true });
    try { const candles = await this.props.api.candles(this.state.instrument, this.state.interval, abort.signal); if (!abort.signal.aborted) this.setState({ candles, error: null }); }
    catch (error) { if (!abort.signal.aborted) this.setState({ error: error instanceof Error ? error.message : 'Candles unavailable.' }); }
    finally { if (!abort.signal.aborted) this.setState({ loading: false }); }
  }
  render() { const items = this.props.snapshot.market?.items ?? []; const selected = items.find(item => item.instrument_id === this.state.instrument); return <div className="content-grid"><div className="stack"><Panel title={selected ? `${selected.symbol} · ${selected.exchange}` : 'Candle chart'} action={<select aria-label="Candle interval" value={this.state.interval} onChange={event => this.setState({ interval: event.target.value, candles: null }, () => { if (this.state.instrument) void this.load(); })}><option>1m</option><option>5m</option><option>15m</option></select>}>{this.state.error && <p className="error-banner" role="alert">{this.state.error}</p>}{this.state.candles?.items.length ? <TradingChart candles={this.state.candles.items} label={`${selected?.symbol} candlestick chart`} /> : <Empty title={this.state.loading ? 'Loading candles…' : this.state.instrument ? 'No candles available' : 'Choose an instrument'}>Select an instrument from the watchlist to inspect its candles.</Empty>}<div className="panel-footer"><span>Intraday candles · IST</span><a href="https://www.tradingview.com/" target="_blank" rel="noreferrer">Charts by TradingView</a></div></Panel><OrderTicket market={this.props.snapshot.market} disabled={this.props.disabled} onAction={this.props.onAction} /></div><Panel title="Watchlist" action={<Badge>{items.length} instruments</Badge>}><ul className="watchlist">{items.map(item => <li key={item.instrument_id}><button aria-pressed={this.state.instrument === item.instrument_id} onClick={() => this.setState({ instrument: item.instrument_id, candles: null, error: null }, () => void this.load())}><div><strong>{item.symbol}</strong><small>{item.exchange} · {Display.time(item.as_of)}</small></div><div><strong>{Display.money(item.last_price)}</strong><small className={Display.tone(item.change_percent)}>{item.change_percent == null ? 'Change unavailable' : `${item.change_percent > 0 ? '+' : ''}${item.change_percent.toFixed(2)}%`}</small></div></button></li>)}</ul>{!items.length && <Empty title="Watchlist is empty">Watchlist instruments are configured on the worker.</Empty>}</Panel></div>; }
}
export class BacktestsView extends Component<ViewProps> { render() { return <Panel title="Backtest research" eyebrow="Coming in a later phase"><div className="backtest-placeholder"><CircleHelp size={36} strokeWidth={1.3} /><h2>A place to test your next hypothesis.</h2><p>Run comparison, equity and drawdown curves, and trade-level analysis will appear here when backtest jobs are exposed by the control API.</p><Badge>Not available in this phase</Badge><div className="placeholder-features"><span>01 · Run comparisons</span><span>02 · Equity & drawdown</span><span>03 · Trade analysis</span></div></div></Panel>; } }
export class SystemView extends Component<ViewProps> {
  render() { const data = this.props.snapshot.system; return <><div className="content-grid"><Panel title="Service health" action={<Button variant="secondary" size="sm" disabled={this.props.disabled} onClick={() => this.props.onAction({ title: 'Reconcile now', description: 'Compare platform and broker state. The worker halts trading if a discrepancy is found.', draft: { type: 'RECONCILE_NOW', params: {} } })}><RefreshCw size={14} /> Reconcile now</Button>}><div className="health-list">{data?.services.map(service => <div key={service.name}><Health name={service.name} healthy={service.healthy} /><p className="muted small">{service.detail}</p></div>)}</div>{!data?.services.length && <Empty title="Health unavailable">Waiting for the API.</Empty>}</Panel><Panel title="Reconciliation history"><EventFeed events={data?.reconciliations ?? []} /></Panel></div><Panel title="Command audit" className="mt-section"><DataTable headings={['Created · IST', 'Command', 'Status', 'Outcome', 'Idempotency key']} rows={(data?.commands ?? []).map(command => ({ id: command.id, cells: [Display.time(command.created_at), command.type, <Badge key="status" tone={['failed', 'rejected', 'expired'].includes(command.status) ? 'negative' : command.status === 'done' ? 'positive' : 'warning'}>{command.status}</Badge>, command.message ?? 'Awaiting worker outcome', <code key="key">{command.idempotency_key}</code>] }))} empty="No commands recorded" /></Panel><Panel title="System events" className="mt-section"><EventFeed events={data?.events ?? []} /></Panel></>; }
}
export class ViewRegistry {
  static readonly pages: Readonly<Record<string, { title: string; subtitle: string; component: typeof OverviewView }>> = {
    '/': { title: 'Session overview', subtitle: 'Your trading session, in focus.', component: OverviewView },
    '/positions': { title: 'Positions', subtitle: 'Exposure, marks and the positions behind your P&L.', component: PositionsView },
    '/orders': { title: 'Orders', subtitle: 'Every intent. Every transition. Every outcome.', component: OrdersView },
    '/strategies': { title: 'Strategies', subtitle: 'Control execution. Keep risk in the loop.', component: StrategiesView },
    '/risk': { title: 'Risk monitor', subtitle: 'Know your limits before the next order.', component: RiskView },
    '/market': { title: 'Market watch', subtitle: 'Cash equity quotes and intraday candles.', component: MarketView },
    '/backtests': { title: 'Backtests', subtitle: 'Research before execution.', component: BacktestsView },
    '/system': { title: 'System', subtitle: 'Operational health and an auditable command trail.', component: SystemView },
  };
  static render(path: string, props: ViewProps): ReactNode { const View = this.pages[path]?.component ?? OverviewView; return <View {...props} />; }
}
