"""`emporos research collect-calendar` and `build-calendar` (EM-244, driver-atlas-plan §3.2).

`collect-calendar` fetches the public pages the calendar is read from, one request at a time and
about 3 s apart, keeps each reply verbatim outside git and ledgers it with its URL and fetch time
(`docs/research/profit/calendar-ledger.jsonl`); a refusal (401, 403, 429) stops the run. It runs on
the development machine only. `build-calendar` reads those pages and the hand-kept rows and writes
the calendar YAML with each event's availability time."""

from __future__ import annotations

import asyncio
from datetime import date
from pathlib import Path

import httpx
import typer

from emporos.core.clock import AsyncioSleeper, SystemClock
from emporos.core.errors import EmporosError
from emporos.core.paths import research_dir
from emporos.research.cause_ledger.events import DEFAULT_CALENDAR_FILE, YamlCalendar
from emporos.research.cause_ledger.expiries import ExpirySource, default_index_source
from emporos.research.cause_ledger.pages import (
    DEFAULT_CALENDAR_LEDGER,
    DEFAULT_CALENDAR_RAW,
    PageCollector,
    PageSpec,
)
from emporos.research.cause_ledger.sources import (
    AlfredSource,
    CalendarBuilder,
    EventSource,
    FedSource,
    GstSource,
    IndexChangeSource,
    ManualSource,
    MospiSource,
)
from emporos.research.filings.collector import CollectionHalted
from emporos.research.filings.polite import PoliteGet, SourceRefused
from emporos.research.filings.raw_store import FetchLedger
from emporos.research.fo_archive_store import FoDayStore

DEFAULT_MANUAL_FILE = Path("config/calendar/manual_events.yaml")

_RAW = typer.Option(
    DEFAULT_CALENDAR_RAW, help="Where each reply is kept verbatim (local, not git)."
)
_LEDGER = typer.Option(DEFAULT_CALENDAR_LEDGER, help="The append-only fetch ledger.")
_GAP = typer.Option(3.0, help="Seconds between requests (at least 1).")
EXPIRY_FILE = Path("config/calendar/fno_expiries.yaml")
_FO_URL = "https://nsearchives.nseindia.com/content/fo/"
_OUT = typer.Option(DEFAULT_CALENDAR_FILE, help="The calendar YAML to write.")
_MANUAL = typer.Option(DEFAULT_MANUAL_FILE, help="Rows kept by hand, each with its source.")


def calendar_pages() -> list[PageSpec]:
    return FedSource.pages() + GstSource.pages() + AlfredSource.pages() + MospiSource.pages()


async def _collect(raw: Path, ledger: Path, gap: float) -> list[str]:
    async with httpx.AsyncClient(timeout=60.0, follow_redirects=True) as client:
        collector = PageCollector(
            PoliteGet(client, AsyncioSleeper(), gap), raw, FetchLedger(ledger), SystemClock()
        )
        return await collector.run(calendar_pages(), typer.echo)


def research_collect_calendar(
    raw: Path = _RAW, ledger: Path = _LEDGER, seconds_between_requests: float = _GAP
) -> None:
    """Fetch the calendar's public source pages (resumable, polite, stops on a refusal)."""
    try:
        failed = asyncio.run(_collect(raw, ledger, seconds_between_requests))
    except SourceRefused as error:
        typer.secho(f"stopped: {error}", fg=typer.colors.RED)
        raise typer.Exit(code=2) from error
    except CollectionHalted as error:
        typer.secho(f"halted: {error}", fg=typer.colors.RED)
        raise typer.Exit(code=2) from error
    except (EmporosError, ValueError, OSError) as error:
        message = error.message if isinstance(error, EmporosError) else str(error)
        typer.secho(f"collect-calendar failed: {message}", fg=typer.colors.RED)
        raise typer.Exit(code=1) from error
    if failed:
        typer.echo(f"re-run to retry: {'; '.join(failed)}")
        raise typer.Exit(code=2)


def _write_expiries(checked: date) -> None:
    """F&O expiry days from whichever archives exist (stock now, index once it is collected)."""
    root = research_dir()
    sources: list[EventSource] = []
    stock = root / "fo_stock_v1"
    if stock.exists():
        sources.append(ExpirySource(FoDayStore(stock), _FO_URL, checked, "stock F&O bhavcopy"))
    index = root / "fo_bhavcopy"
    if index.exists():
        sources.append(default_index_source(index, checked))
    if sources:
        YamlCalendar(EXPIRY_FILE).write(
            CalendarBuilder(sources).build(),
            "# Generated by `research build-calendar` from the F&O archives; do not edit.\n",
        )


def research_build_calendar(raw: Path = _RAW, out: Path = _OUT, manual: Path = _MANUAL) -> None:
    """Write the calendar YAML (2017-11-01..2026-03-18) from the fetched pages and manual rows."""
    try:
        checked = SystemClock().now().date()
        sources: list[EventSource] = [
            FedSource(raw, checked),
            GstSource(raw, checked),
            AlfredSource(raw, checked),
            MospiSource(raw, checked),
            ManualSource(manual),
            IndexChangeSource(Path("config/universe/d1/index-changes.yaml"), checked),
        ]
        events = CalendarBuilder(sources).build()
        count = YamlCalendar(out).write(
            events, "# Generated by `research build-calendar`; do not edit by hand.\n"
        )
        _write_expiries(checked)
    except (EmporosError, ValueError, OSError, KeyError) as error:
        message = error.message if isinstance(error, EmporosError) else str(error)
        typer.secho(f"build-calendar failed: {message}", fg=typer.colors.RED)
        raise typer.Exit(code=1) from error
    kinds: dict[str, int] = {}
    for event in events:
        kinds[event.kind] = kinds.get(event.kind, 0) + 1
    typer.echo(f"{count} events in {out}: {kinds}")
